name: Build and Deploy React App CMS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build React app
        env:
          REACT_APP_BASE_URL: ${{ vars.REACT_APP_BASE_URL }}
          REACT_APP_CLIENT_ID: ${{ vars.REACT_APP_CLIENT_ID }}
          REACT_APP_ROUTER_BASE_NAME: ${{ vars.REACT_APP_ROUTER_BASE_NAME }}
        run: npm run build

      - name: Zip build artifacts
        run: |
          cd build
          zip -r ../${GITHUB_REPOSITORY##*/}.zip .
          cd ..

      - name: Get access token
        id: token
        run: |
          TOKEN=$(curl -s --location '${{ vars.ACTION_TOKEN_SERVICE }}/o/token/' \
            --header "Authorization: Basic ${{ secrets.ACTION_TOKEN_CREDS }}" \
            --header 'Content-Type: application/x-www-form-urlencoded' \
            --data-urlencode 'grant_type=client_credentials' \
            --data-urlencode 'scope=read' | jq -r '.access_token')

          echo "access_token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Upload build ZIP
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.token.outputs.access_token }}" \
            -F "build_file=@${GITHUB_REPOSITORY##*/}.zip" \
            ${{ vars.CMS_DEPLOY_API_URL }}
